name: Test GH Pages Deploy

on:
  pull_request:
    branches:
      - master

env:
  NODE_ENV: production

jobs:
  test-deploy:
    name: Test docusaurus build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Install dependencies
        run: yarn install
      - name: Test build
        env:
          NODE_ENV: ${{ env.NODE_ENV }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_API_URL: ${{ secrets.POSTHOG_API_URL }}
        run: yarn build
